import {
  AmazonWebServicesDark,
  AppleDark,
  Bun,
  ClaudeAI,
  Cloudflare,
  DenoDark,
  DigitalOcean,
  Docker,
  Firebase,
  Gemini,
  GitHubDark,
  GitLab,
  GoDark,
  GoogleCloud,
  Heroku,
  Java,
  Kubernetes,
  Linux,
  MariaDB,
  MicrosoftAzure,
  MongoDBDark,
  MySQLDark,
  Neon,
  Netlify,
  Nextjs,
  Nginx,
  Nodejs,
  OpenAIDark,
  PostgreSQL,
  Python,
  RailwayDark,
  RaspberryPI,
  ReactDark,
  Redis,
  RenderDark,
  RustDark,
  SQLite,
  Supabase,
  Svelte,
  Ubuntu,
  VercelDark,
  Vue,
  Windows,
  TailwindCSS,
  TypeScript,
  JavaScript,
  Vim,
  Neovim,
  Discord,
  Slack,
  GraphQL,
  AnthropicDark,
  AstroDark,
  BashDark,
  Bitcoin,
  Ethereum,
  Tauri,
} from "@ridemountainpig/svgl-react";

export type BrandIconEntry = {
  id: string;
  label: string;
  Icon: (props: React.SVGProps<SVGSVGElement>) => React.JSX.Element;
};

export const BRAND_ICONS: BrandIconEntry[] = [
  { id: "linux", label: "Linux", Icon: Linux },
  { id: "ubuntu", label: "Ubuntu", Icon: Ubuntu },
  { id: "raspberrypi", label: "Raspberry Pi", Icon: RaspberryPI },
  { id: "apple", label: "Apple", Icon: AppleDark },
  { id: "windows", label: "Windows", Icon: Windows },
  { id: "docker", label: "Docker", Icon: Docker },
  { id: "kubernetes", label: "Kubernetes", Icon: Kubernetes },
  { id: "aws", label: "AWS", Icon: AmazonWebServicesDark },
  { id: "azure", label: "Azure", Icon: MicrosoftAzure },
  { id: "gcp", label: "Google Cloud", Icon: GoogleCloud },
  { id: "cloudflare", label: "Cloudflare", Icon: Cloudflare },
  { id: "digitalocean", label: "DigitalOcean", Icon: DigitalOcean },
  { id: "heroku", label: "Heroku", Icon: Heroku },
  { id: "vercel", label: "Vercel", Icon: VercelDark },
  { id: "netlify", label: "Netlify", Icon: Netlify },
  { id: "railway", label: "Railway", Icon: RailwayDark },
  { id: "render", label: "Render", Icon: RenderDark },
  { id: "github", label: "GitHub", Icon: GitHubDark },
  { id: "gitlab", label: "GitLab", Icon: GitLab },
  { id: "nginx", label: "Nginx", Icon: Nginx },
  { id: "nodejs", label: "Node.js", Icon: Nodejs },
  { id: "bun", label: "Bun", Icon: Bun },
  { id: "deno", label: "Deno", Icon: DenoDark },
  { id: "python", label: "Python", Icon: Python },
  { id: "go", label: "Go", Icon: GoDark },
  { id: "rust", label: "Rust", Icon: RustDark },
  { id: "java", label: "Java", Icon: Java },
  { id: "react", label: "React", Icon: ReactDark },
  { id: "nextjs", label: "Next.js", Icon: Nextjs },
  { id: "vue", label: "Vue", Icon: Vue },
  { id: "svelte", label: "Svelte", Icon: Svelte },
  { id: "postgres", label: "PostgreSQL", Icon: PostgreSQL },
  { id: "mysql", label: "MySQL", Icon: MySQLDark },
  { id: "mariadb", label: "MariaDB", Icon: MariaDB },
  { id: "mongodb", label: "MongoDB", Icon: MongoDBDark },
  { id: "redis", label: "Redis", Icon: Redis },
  { id: "sqlite", label: "SQLite", Icon: SQLite },
  { id: "neon", label: "Neon", Icon: Neon },
  { id: "supabase", label: "Supabase", Icon: Supabase },
  { id: "firebase", label: "Firebase", Icon: Firebase },
  { id: "openai", label: "OpenAI", Icon: OpenAIDark },
  { id: "claude", label: "Claude", Icon: ClaudeAI },
  { id: "gemini", label: "Gemini", Icon: Gemini },
  { id: "anthropic", label: "Anthropic", Icon: AnthropicDark },
  { id: "tailwindcss", label: "Tailwind CSS", Icon: TailwindCSS },
  { id: "typescript", label: "TypeScript", Icon: TypeScript },
  { id: "javascript", label: "JavaScript", Icon: JavaScript },
  { id: "vim", label: "Vim", Icon: Vim },
  { id: "neovim", label: "Neovim", Icon: Neovim },
  { id: "discord", label: "Discord", Icon: Discord },
  { id: "slack", label: "Slack", Icon: Slack },
  { id: "graphql", label: "GraphQL", Icon: GraphQL },
  { id: "astro", label: "Astro", Icon: AstroDark },
  { id: "bash", label: "Bash", Icon: BashDark },
  { id: "bitcoin", label: "Bitcoin", Icon: Bitcoin },
  { id: "ethereum", label: "Ethereum", Icon: Ethereum },
  { id: "tauri", label: "Tauri", Icon: Tauri },
];

export const BRAND_ICON_MAP: Record<string, BrandIconEntry> = Object.fromEntries(
  BRAND_ICONS.map((b) => [b.id, b]),
);
