import {
  Activity,
  ArrowSeparate,
  AtSign,
  AtSignCircle,
  BellNotificationSolid,
  BitcoinCircleSolid,
  Bitbucket,
  Bookmark,
  BookmarkBook,
  BookmarkCircle,
  Box,
  Brain,
  BugSolid,
  CashSolid,
  ChatBubbleSolid,
  Clock,
  Cloud,
  CloudSync,
  Code,
  CoolingSquareSolid,
  Cpu,
  Css3,
  Cube,
  Database,
  DatabaseSolid,
  DataTransferDown,
  DataTransferUp,
  Download,
  EthereumCircle,
  EthereumCircleSolid,
  EuroSquareSolid,
  Eye,
  FacetimeSolid,
  Fingerprint,
  FireFlame,
  Flash,
  Flask,
  Frame,
  GitBranch,
  GitPullRequest,
  Globe,
  GoogleDrive,
  GoogleOne,
  Group,
  HalfMoon,
  HardDrive,
  Hexagon,
  Home,
  HomeAlt,
  Html5,
  Internet,
  KanbanBoard,
  Key,
  Laptop,
  LaptopDevMode,
  Linux,
  Lock,
  MacControlKey,
  MailOpenSolid,
  Map,
  Mastodon,
  MessageSolid,
  MoneySquareSolid,
  MultiBubbleSolid,
  MultiplePages,
  NavArrowLeft,
  NavArrowRight,
  Network,
  Npm,
  Package,
  PasswordCheck,
  PhoneSolid,
  Pin,
  Planet,
  PolarSh,
  ProfileCircle,
  Refresh,
  Repeat,
  Rocket,
  Search,
  SendDiagonalSolid,
  SendMailSolid,
  Server,
  ServerConnection,
  Settings,
  SettingsProfiles,
  ShieldCheck,
  SmartphoneDevice,
  SnowFlake,
  Spotify,
  Star,
  StarSolid,
  StatsReport,
  SunLight,
  SystemRestart,
  Terminal,
  Thunderstorm,
  TiktokSolid,
  Timer,
  Upload,
  User,
  UserBadgeCheck,
  VueJs,
  WebWindowSolid,
  WhatsappSolid,
  Wifi,
  WifiSignalNoneSolid,
  Windows,
  WolfSolid,
  YoutubeSolid,
} from "iconoir-react";
import type { ForwardRefExoticComponent, RefAttributes, SVGProps } from "react";

type IconoirIconComponent = ForwardRefExoticComponent<
  Omit<SVGProps<SVGSVGElement>, "ref"> & RefAttributes<SVGSVGElement>
>;

export type IconoirIconEntry = {
  id: string;
  label: string;
  exportName: string;
  Icon: IconoirIconComponent;
};

const LABEL_OVERRIDES: Record<string, string> = {
  AtSign: "At Sign",
  Cpu: "CPU",
  Css3: "CSS 3",
  Html5: "HTML 5",
  Npm: "npm",
  VueJs: "Vue.js",
};

const toWords = (name: string) =>
  name
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2")
    .replace(/([A-Za-z])(\d)/g, "$1 $2")
    .replace(/(\d)([A-Za-z])/g, "$1 $2");

const entry = (id: string, name: string, Icon: IconoirIconComponent): IconoirIconEntry => ({
  id,
  label: LABEL_OVERRIDES[name] ?? toWords(name),
  exportName: name,
  Icon,
});

export const ICONOIR_ICONS: IconoirIconEntry[] = (
  [
    ["server", "Server", Server],
    ["server-connection", "ServerConnection", ServerConnection],
    ["terminal", "Terminal", Terminal],
    ["code", "Code", Code],
    ["cloud", "Cloud", Cloud],
    ["cloud-sync", "CloudSync", CloudSync],
    ["internet", "Internet", Internet],
    ["network", "Network", Network],
    ["wifi", "Wifi", Wifi],
    ["database", "Database", Database],
    ["hard-drive", "HardDrive", HardDrive],
    ["cpu", "Cpu", Cpu],
    ["activity", "Activity", Activity],
    ["stats-report", "StatsReport", StatsReport],
    ["shield-check", "ShieldCheck", ShieldCheck],
    ["lock", "Lock", Lock],
    ["key", "Key", Key],
    ["fingerprint", "Fingerprint", Fingerprint],
    ["password-check", "PasswordCheck", PasswordCheck],
    ["flash", "Flash", Flash],
    ["brain", "Brain", Brain],
    ["cube", "Cube", Cube],
    ["package", "Package", Package],
    ["git-branch", "GitBranch", GitBranch],
    ["git-pull-request", "GitPullRequest", GitPullRequest],
    ["search", "Search", Search],
    ["eye", "Eye", Eye],
    ["fire-flame", "FireFlame", FireFlame],
    ["rocket", "Rocket", Rocket],
    ["planet", "Planet", Planet],
    ["box", "Box", Box],
    ["frame", "Frame", Frame],
    ["bookmark", "Bookmark", Bookmark],
    ["bookmark-circle", "BookmarkCircle", BookmarkCircle],
    ["hexagon", "Hexagon", Hexagon],
    ["flask", "Flask", Flask],
    ["multiple-pages", "MultiplePages", MultiplePages],
    ["system-restart", "SystemRestart", SystemRestart],
    ["data-transfer-up", "DataTransferUp", DataTransferUp],
    ["data-transfer-down", "DataTransferDown", DataTransferDown],
    ["upload", "Upload", Upload],
    ["download", "Download", Download],
    ["settings", "Settings", Settings],
    ["settings-profiles", "SettingsProfiles", SettingsProfiles],
    ["profile-circle", "ProfileCircle", ProfileCircle],
    ["user", "User", User],
    ["user-badge-check", "UserBadgeCheck", UserBadgeCheck],
    ["group", "Group", Group],
    ["home", "Home", Home],
    ["home-alt", "HomeAlt", HomeAlt],
    ["globe", "Globe", Globe],
    ["map", "Map", Map],
    ["laptop", "Laptop", Laptop],
    ["smartphone-device", "SmartphoneDevice", SmartphoneDevice],
    ["mac-control-key", "MacControlKey", MacControlKey],
    ["nav-arrow-right", "NavArrowRight", NavArrowRight],
    ["nav-arrow-left", "NavArrowLeft", NavArrowLeft],
    ["arrow-separate", "ArrowSeparate", ArrowSeparate],
    ["repeat", "Repeat", Repeat],
    ["refresh", "Refresh", Refresh],
    ["timer", "Timer", Timer],
    ["clock", "Clock", Clock],
    ["bookmark-book", "BookmarkBook", BookmarkBook],
    ["pin", "Pin", Pin],
    ["star", "Star", Star],
    ["star-solid", "StarSolid", StarSolid],
    ["half-moon", "HalfMoon", HalfMoon],
    ["sun-light", "SunLight", SunLight],
    ["snow-flake", "SnowFlake", SnowFlake],
    ["thunderstorm", "Thunderstorm", Thunderstorm],
    ["windows", "Windows", Windows],
    ["web-window-solid", "WebWindowSolid", WebWindowSolid],
    ["linux", "Linux", Linux],
    ["wolf-solid", "WolfSolid", WolfSolid],
    ["google-drive", "GoogleDrive", GoogleDrive],
    ["google-one", "GoogleOne", GoogleOne],
    ["bell-notification-solid", "BellNotificationSolid", BellNotificationSolid],
    ["at-sign-circle", "AtSignCircle", AtSignCircle],
    ["at-sign", "AtSign", AtSign],
    ["chat-bubble-solid", "ChatBubbleSolid", ChatBubbleSolid],
    ["facetime-solid", "FacetimeSolid", FacetimeSolid],
    ["mail-open-solid", "MailOpenSolid", MailOpenSolid],
    ["message-solid", "MessageSolid", MessageSolid],
    ["phone-solid", "PhoneSolid", PhoneSolid],
    ["multi-bubble-solid", "MultiBubbleSolid", MultiBubbleSolid],
    ["send-mail-solid", "SendMailSolid", SendMailSolid],
    ["send-diagonal-solid", "SendDiagonalSolid", SendDiagonalSolid],
    ["wifi-signal-none-solid", "WifiSignalNoneSolid", WifiSignalNoneSolid],
    ["database-solid", "DatabaseSolid", DatabaseSolid],
    ["bug-solid", "BugSolid", BugSolid],
    ["vue-js", "VueJs", VueJs],
    ["kanban-board", "KanbanBoard", KanbanBoard],
    ["laptop-dev-mode", "LaptopDevMode", LaptopDevMode],
    ["css3", "Css3", Css3],
    ["html5", "Html5", Html5],
    ["npm", "Npm", Npm],
    ["bitcoin-circle-solid", "BitcoinCircleSolid", BitcoinCircleSolid],
    ["cash-solid", "CashSolid", CashSolid],
    ["ethereum-circle", "EthereumCircle", EthereumCircle],
    ["ethereum-circle-solid", "EthereumCircleSolid", EthereumCircleSolid],
    ["euro-square-solid", "EuroSquareSolid", EuroSquareSolid],
    ["money-square-solid", "MoneySquareSolid", MoneySquareSolid],
    ["bitbucket", "Bitbucket", Bitbucket],
    ["spotify", "Spotify", Spotify],
    ["cooling-square-solid", "CoolingSquareSolid", CoolingSquareSolid],
    ["whatsapp-solid", "WhatsappSolid", WhatsappSolid],
    ["youtube-solid", "YoutubeSolid", YoutubeSolid],
    ["mastodon", "Mastodon", Mastodon],
    ["tiktok-solid", "TiktokSolid", TiktokSolid],
    ["polar-sh", "PolarSh", PolarSh],
  ] satisfies Array<[string, string, IconoirIconComponent]>
).map(([id, name, Icon]) => entry(id, name, Icon));

export const ICONOIR_ICON_MAP: Record<string, IconoirIconEntry> = Object.fromEntries(
  ICONOIR_ICONS.map((b) => [b.id, b]),
);
